name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Linter
        run:
          install flake8
          make lint
      - name: Install pipenv
        run: pip install pipenv
      - name: Install pytest
        run: pip install pytest
             pip install pytest-cov
      - name: Run tests with pytest
        run: pipenv run pytest
      - name: CodeClimat
        run: pip install poetry
             make install
      - uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 5383f93b8b0ed083d1d33bb727e66a6c68fd0964f26d2e90b7b93390b85f66ac
        with:
          coverageCommand: make test-coverage
